<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>a5udf</string>
		<string>a5scr</string>
		<string>a5class</string>
	</array>
	<key>name</key>
	<string>Alpha Anywhere XBASIC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?i:'|REM)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.xbasic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(\n|\r))</string>
			<key>name</key>
			<string>comment.line.apostrophe.xbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Functions</string>
			<key>match</key>
			<string>([a-zA-Z_][a-zA-Z\d_\.:]*)\(</string>
			<key>name</key>
			<string>entity.name.function.xbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>End Function</string>
			<key>match</key>
			<string>\)</string>
			<key>name</key>
			<string>entity.name.function.xbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control Structures</string>
			<key>match</key>
			<string>^[ \t]*(?i:(((END(\s)?)?(FUNCTION|IF|SELECT|WITH|WHILE|CLASS|ENUM))|(GOTO))|(CASE|DIM|REDIM|ELSE|END DEF|EXIT FOR|FOR|NEXT|ON|ON ERROR GOTO|ON ERROR RESUME|SELECT|DEFINE CLASS|CONTINUE|WEND|WHILE|EXIT WHILE|LET|RESUME|RETURN|STOP|DECLARE|UNDECLARE|MACRO|ENUM))</string>
			<key>name</key>
			<string>keyword.control.xbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control Structures</string>
			<key>match</key>
			<string>(?i:(THEN|AS))</string>
			<key>name</key>
			<string>keyword.control.xbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control Structures</string>
			<key>match</key>
			<string>^[ \t]*(?i:(IMPLEMENTATION|NAMESPACE))[ \t]</string>
			<key>name</key>
			<string>keyword.control.xbasic</string>
		</dict>			
		<dict>
			<key>comment</key>
			<string>Control Structures</string>
			<key>match</key>
			<string>(?i:EXIT(\s)(FUNCTION|WHILE|FOR))</string>
			<key>name</key>
			<string>keyword.control.xbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Tagged Strings</string>
			<key>begin</key>
			<string>&lt;&lt;(%[^%]+%)</string>
			<key>end</key>
			<string>\1</string>
			<key>name</key>
			<string>string.quoted.double.xbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Strings</string>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.quoted.double.xbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Variables</string>
			<key>match</key>
			<string>([a-zA-Z_][a-zA-Z\d_]*)</string>
			<key>name</key>
			<string>variable.other.xbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Digits</string>
			<key>match</key>
			<string>(\d+)</string>
			<key>name</key>
			<string>constant.numeric.xbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operators</string>
			<key>match</key>
			<string>(?i:\*|\/|\+|-|$|=|&lt;&gt;|&gt;&lt;|&lt;|&gt;|&lt;=|&gt;=|=&lt;|=&gt;|:|,|;|\(|\)|\[|\]|.NOT.|.AND.|.OR.|.GT.|.LT.|.EQ.|.LE.|.GE.)</string>
			<key>name</key>
			<string>keyword.operator.xbasic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.xbasic</string>
	<key>uuid</key>
	<string>793CF292-D009-4666-AF8F-7C0440AB045B</string>
</dict>
</plist>